<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */
?>
<script>
    require([
        "jquery"
    ], function ($) {
        "use strict";

        $('.config-diff-action').on('click', function() {
            var caller = this;
            var sibling = $(caller).parent().next();
            var path = $(sibling).find(".path").text();
            var scope = $(sibling).find(".scope").text();
            var scopeId = $(sibling).find(".scope-id").text();
            var url = $(sibling).find(".update-url").text();

            $.ajax({
                url: url,
                type: "GET",
                data: {'path': path, 'scope': scope, 'scopeId': scopeId},
                success: function () {
                    var parent = $(caller).parent().parent();
                    var toReplace = $(parent).find('.value')[0];
                    var replace = $(parent).find('.value')[1];
                    $(toReplace).replaceWith(replace);
                    $(parent).parent().find('.sync').remove();
                }
            });
        });
    });
</script>