<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */
?>
<?php /* @var $block \Magenerds\SystemDiff\Block\System\Config\Form\SyncButton */ ?>
<script>
require(
    ['jquery', 'prototype'],
    function(jQuery){

        function enableSyncButton() {
            Form.Element.enable('<?php echo $block->getElement()->getHtmlId() ?>');
            jQuery('#<?php echo $block->getElement()->getHtmlId() ?>').removeClass('disabled');
        }

        function disableSyncButton() {
            Form.Element.disable('<?php echo $block->getElement()->getHtmlId() ?>');
            jQuery('#<?php echo $block->getElement()->getHtmlId() ?>').addClass('disabled');
        }

        Event.observe(window, 'load', function(){
            enableSyncButton();
        });

        jQuery('#<?php echo $block->getElement()->getHtmlId() ?>').click(
            function () {
                disableSyncButton();
                jQuery.get(
                    '<?php echo /* @escapeNotVerified */ $block->getAjaxUrl() ?>'
                ).always(function(){
                    enableSyncButton();
                })
                ;
            }
        );
    }
);
</script>

<?php echo $block->getButtonHtml() ?>